name: Workflow 1 - Lint Code
on: push
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Initialize ESLint
        run: npm init @eslint/config

      - name: Lint
        run: npm run lint

      - name: Test Code
        run: npm test

      - name: Deploy
        run: echo "Deploying application..."
