name: Workflow 1 - Lint Code

on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

        

